#!/usr/bin/env bash
# Script: Test Launcher
# Author: Prof. Juan Medina
# Email: jmedina@collin.edu
# Date: Mar 2025
# Description: Mid-Term and Final Test Launcher

if [ -z "$1" ]; then
  echo "Error: No parameter provided."
  echo "Usage: $0 <midterm|final>"
  exit 1
fi

if [ "$1" = "midterm" ] || [ "$1" = "final" ]
then
  username=$(id -un)
  read -p "Enter your numeric student id: " student_id
  sudo /usr/bin/final ${1} ${student_id} ${username}
else
  echo "Error: Invalid parameter '$1'."
  echo "Usage: $0 <midterm|final>"
  exit 1
fi
